// This is just some sample data so you don't have to think of your own!
const restaurant =
    {
       name: 'South Main Market',
       url: '/store/south-main-market',
       latitude: 35.135502,
       longitude: -90.058657,
       address: "409 South Main Street, Memphis, Tennessee, 38103",
       phone: '901-341-3838',
       hours1:'Tuesday thru Friday 7:30 AM to 10:00 PM',
       hours2:'Saturday and Sunday 10:00 AM to 5:00 PM',
       image:'images/southMainMarket.png',
       site:'https://thesouthmainmarket.com/',
       facebook:'https://www.facebook.com/The-South-Main-Market-572931696202917/',
       instagram:'http://instagram.com/thesouthmainmarket',
       caption:'Welcome to the South Main Market. The first food hall in Memphis. Photo of city east bagel and grill with a happy group chatting and enjoying themselves.',
       summary:'Large location on three levels. With various food stalls mostly on the second floor. Go up the interior stairs. When at the top, JAVA CABANA WEST, will be on your left. CITY EAST BAGEL AND GRILL will be on the right just after Wall Flower Memphis. Then walk a little farther and find Kinfolk on the right. Counter service at all stalls. You will find seating in the middle. Ask and your drinks and food can be delivered to your table. Service dogs will love this place. A casual community hang out with free wifi. Located on the South Main street bus and trolley lines.  If you love this menu ask to talk to the manager or owner thank you. They are our first customers!',
       bus:'Main Street Line - Bus 100 - Stop Name: Huling - Main Tro NB Stop',
       cab:'Easy cap drop off directly in front',
       menuBlocks:
       [
           {
               heading:'CITY BLOCK SALUMERIA - Meats & Charcutarie Items - $7.00 to $35.00',
               menuItems: [
                   {item : 'BEEF ITEMS'},
                   {item : '1. Brisket - PRICE $12.00 a pound'},
                   {item : '2. Eye Round - PRICE $10.00 a pound'},
                   {item : '3. Back Ribs - PRICE $9.00 a pound'},
                   {item : '4. Ribeye - PRICE $19.00 a pound'},
                   {item : '5. Dry Aged Ribeye - PRICE $25.00 a pound'},
                   {item : '6. Cowboy Ribeye - PRICE $25.00 a pound'},
                   {item : '7. Spinalis - PRICE $35.00 a pound'},
                   {item : '8. Saratoga - PRICE $29.00 a pound'},
                   {item : '9. Porterhouse - PRICE $24.00 a pound'},
                   {item : '10. T Bone - PRICE $17.00 a pound'},
                   {item : '11. Tenderloin - PRICE $29.00 a pound'},
                   {item : '12. Bone in Filet - PRICE $27.00 a pound'},
                   {item : '13. New York Strip - PRICE $19.00 a pound'},
                   {item : '14. Kansas City Strip - PRICE $19.00 a pound'},
                   {item : '15. Steak Burger - PRICE $12.00 a pound'},
                   {item : '16. Ground Beef - PRICE $9.00 a pound'},
                   {item : 'BEEF AND LAMB SAUSAGES - City Block Salumeria items '},
                   {item : '17. Fresh - PRICE $12.00 a pound'},
                   {item : '18. Hot Dogs - PRICE $12.00 a pound'},
                   {item : 'PORK - City Block Salumeria items'},
                   {item : '19. Belly - PRICE $8.00 a pound'},
                   {item : '20. Coppa - PRICE $12.00 a pound'},
                   {item : '21. Rib Chop - PRICE $10.00 a pound'},
                   {item : '22. Porterhouse Chop - PRICE $9.00 a pound'},
                   {item : '23. Shoulder / Butt - PRICE $8.00 a pound'},
                   {item : '24. Ground Pork - PRICE $8.00 a pound'},
                   {item : 'PORK SAUSAGES - City Block Salumeria items '},
                   {item : '25. Fresh - PRICE $9.00 a pound'},
                   {item : '26. Smoked - PRICE $10.00 a pound'},
                   {item : '27. Mortadella - PRICE $15.00 a pound'},
                   {item : 'COOKED AND CURED MEATS - City Block Salumeria items '},
                   {item : '28. PORK - Ham, Bacon, Gabagool - PRICE $12.00 a pound'},
                   {item : '29. BEEF - Pastrami and Corned Beef - PRICE $15.00 a pound'},
                   {item : '30. Pate - PRICE $8.00 a pound'},
                   {item : '31. Headcheese - PRICE $12.00 a pound'},
                   {item : 'CHARCUTERIE & MISC - City Block Salumeria items'},
                   {item : '32. Whole Muscle - PRICE $12.00 for 20 slices'},
                   {item : '33. Salami which is fermented - PRICE $18.00 each for smaller size'},
                   {item : '34. Salami Sec - PRICE $12.00 each'},
                   {item : '35. Jerky - PRICE $10.00 per bag'},
                   {item : '36. Prosciutto - PRICE $45.00 a pound'},
                   {item : '37. Gravlax - PRICE $15.00 a pound'},
                   {item : '38. Pasnc., Guanc, Lardo  - PRICE $22.00 a pound each'},
                   {item : '39. Lard - PRICE $5.00 per quart'},
                   {item : '40. Schmaltz - PRICE $5.00 per cup'},
                   {item : '41. Duck Fat - PRICE $10.00 per cup'},
                   {item : '42. Stocks - PRICE $6.00 per quart'},
                   {item : '43. Bar B Q Sauce - PRICE $6.00 per jar'},
                   {item : '44. Demi - PRICE $7.00 per cup'},
                   {item : '43. Pickles - PRICE $8.00 per jar'},
               ],
           },
           {
               heading:'CITY BLOCK SALUMERIA - 7 Breakfast Sandwiches - $5.00 to $12.00',
               menuItems: [
                   {item : 'Breakfast served Tuesday and Friday from 7:30 to 10:30. Saturday and Sunday brunch starts at 10:00. All breakfast sandwiches served on a kaiser roll.'},
                   {item : '1. Bacon, egg, and american cheese breakfast sandwich - PRICE $7.50'},
                   {item : '2. City ham, egg, and american cheese breakfast sandwich - PRICE $7.50'},
                   {item : '3. Spicy maple sausage, egg, and american cheese breakfast sandwich - PRICE $7.50'},
                   {item : '4. Egg and american cheese breakfast sandwich - PRICE $5.50'},
                   {item : '5. DAVES BAGEL WITH SCHMEAR - PRICE $5.00'},
                   {item : '6. DAVES BAGEL WITH LOX and SCHMEAR - PRICE $12.00'},
                   {item : '7. Add house made pepperoncini - PRICE .50 cents'},
               ],
           },
           {
               heading:'CITY BLOCK SALUMERIA - 13 Speciality & Regular Sandwiches - $8.00 to $35.00',
               menuItems: [
                   {item : 'Lunch served daily from 11:00 to 7:30.'},
                   {item : '1. THE HOT ITALIAN  - Capicola, soppressata, mortadella, city ham and spuma di n duja on Leidenheimer’s french baguette with provolone cheese, pepperoncini, marinated onions and green leaf lettuce. - PRICE $10.00'},
                   {item : '2. THE CUBAN - Smoked pork shoulder and city ham on pressed Leidenheimer’s french baguette with swiss cheese, yellow mustard and pickles. - PRICE $10.00'},
                   {item : '3. MUFFALETTA - Capicola, mortadella and soppressata on Gambino muffaletta loaf with provolone cheese and olive salad. - PRICE  Whole $35.00, Half $18.00 and Quarter $9.00'},
                   {item : '4. THE REUBEN  - Pastrami on rye bread with swiss cheese, sauerkraut and Russian dressing. - PRICE $9.00'},
                   {item : '5. THE CLASSIC HOT HAM AND CHEESE - City ham on kaiser roll with american cheese. - PRICE $8.00'},
                   {item : '6. GRILLED PIMIENTO CHEESE - Pimiento cheese on rye bread with local tomato, when in season - PRICE $8.00'},
                   {item : '7. HAM AND SWISS - Ham and swiss cheese with Dijon mayonnaise served on Leidenheimers french baguette with green leaf lettuce, local tomato when in season, pepperrboncini and marinated onion. - PRICE $9.00'},
                   {item : '8. PASTRAMI AND SWISS - Pastrami and swiss cheese with creole mustard served on Leidenheimers french baguette with green leaf lettuce, local tomato when in season, pepperrboncini and marinated onion. - PRICE $9.00'},
                   {item : '9. ROAST BEEF - Roast Beef and provolone cheese with horseradish and roasted garlic mayonnaise served on Leidenheimers french baguette with green leaf lettuce, local tomato when in season, pepperrboncini and marinated onion. - PRICE $9.00'},
                   {item : '10. TURKEY - Turkey and provolone cheese with dijon mayonnaise served on Leidenheimers french baguette with green leaf lettuce, local tomato when in season, pepperrboncini and marinated onion. - PRICE $9.00'},
                   {item : 'SANDWICH EXTRAS '},
                   {item : '11. Extra meat - PRICE $3.00'},
                   {item : '12. Extra cheese - PRICE $1.00'},
                   {item : '13. Extra pickles or pepperoncini - PRICE .50 cents'},
               ],
           },
           {
               heading:'CITY BLOCK SALUMERIA - 4 Sides - $2.00',
               menuItems: [
                   {item : '1. Potato Salad - PRICE $2.00'},
                   {item : '2. Cole Slaw - PRICE $2.00'},
                   {item : '3. Dirty Potato Chips - PRICE $2.00'},
                   {item : '4. Cumcumber Salad - PRICE $2.00'},

               ],
           },
           {
               heading:'JAVA CABANA WEST - 31 Coffees, Mochas and Specialities Drinks $2.25 to $5.45',
               menuItems: [
                   {item : '1. CUP OF COFFEE - PRICE $2.25'},
                   {item : '2. AMERICANO COFFEE - PRICE $2.85'},
                   {item : '3. CAFE AU LAIT - PRICE $3.00'},
                   {item : '4. BREVE COFFEE - PRICE $4.45'},
                   {item : '5. CHAI - PRICE $3.95'},
                   {item : '6. DIRTY CHAI - PRICE $4.70'},
                   {item : '7. ESPRESSO DOUBLE - PRICE $2.50'},
                   {item : '8. CAPPUCCINO - PRICE $3.95'},
                   {item : '9. LATTE - PRICE $3.95'},
                   {item : '10. VANILLA LATTE - PRICE $4.45'},
                   {item : '11. FANCY CARAMEL LATTE - PRICE $4.75'},
                   {item : 'EXTRAS'},
                   {item : '12. SOY MILK - PRICE 75 cents'},
                   {item : '13. ALMOND MILK - PRICE 75 cents'},
                   {item : '14. MOCHA - PRICE $4.50'},
                   {item : '15. RASPBERRY MOCHA - PRICE $4.75'},
                   {item : '16. LAVENDER MOCHA - PRICE $4.75'},
                   {item : '17. ALMOMD MOCHA - PRICE $4.75'},
                   {item : '18. HAZELNUT MOCHA - PRICE $4.75'},
                   {item : '19. HOT TEA - PRICE $2.75'},
                   {item : '20. MYSTERY TRAIN - Hazelnut, vanilla, espresso, steamed milk and whip cream - PRICE $4.95'},
                   {item : '21. FUNKY MONKEY - Chocolate, banana syrup, espresso, steamed milk and whip cream - PRICE $4.95'},
                   {item : '22. CHOCOLATE DREAM - Orange syrup, chocolate, espresso, steamed milk and whip cream - PRICE $4.95'},
                   {item : '23. SWEET JANE -Caramel sauce, vanilla, espresso, steamed milk and whip cream - PRICE $4.95'},
                   {item : '24. ICED LATTE - PRICE $4.45'},
                   {item : '25. ICED VANILLA LATTE - PRICE $4.95'},
                   {item : '26. ICED MOCHA - PRICE $4.99'},
                   {item : '27. ICED CHAI - PRICE $4.45'},
                   {item : '28. ICED MYSTERY TRAIN - Hazelnut, vanilla, espresso, steamed milk and whip cream - PRICE $5.45'},
                   {item : '29. ICED FUNKY MONKEY - Chocolate, banana syrup, espresso, steamed milk and whip cream - PRICE $5.45'},
                   {item : '30. ICED CHOCOLATE DREAM - Orange syrup, chocolate, espresso, steamed milk and whip cream  - PRICE $5.45'},
                   {item : '31. ICED WEET JANE -Caramel sauce, vanilla, espresso, steamed milk and whip cream  - PRICE $5.45'},
               ]
           }
       ]
   }

  export default restaurant;
